[package]
name = "session"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
actix-session = {version = "0.6", features = ["cookie-session"]}
thiserror = "1.0"
serde_json = "1.0"

[dev-dependencies]
actix-web = {version = "4"}